name: t_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

#---------------------- Packages ----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0

  # icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # state management
  get: ^4.6.5
  get_storage: ^2.1.1

  # product specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1


#---------------------- ./ Packages End ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/profile/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
